version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toto
      MYSQL_DATABASE: taskmasterpro
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
    command: --lower-case-table-names=1
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      custom-network:
        ipv4_address: 10.0.0.2

  task_master_pro_backend:
    image : task_master_pro_backend
    container_name: taskpro
    stdin_open: true
    tty: true
    ports:
      - "5240:5240"
    depends_on:
      - mysql
    networks:
      custom-network:
        ipv4_address: 10.0.0.10

networks:
  custom-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

volumes:
  mysql-data:
